### PR TITLE
make sure PR doesn't break build

### PR DESCRIPTION
**Pull request by Lenni009**

### CODE REVIEW

**Comment by Lenni009** [comment]
This action should be configured to block PRs to the `main` branch if it fails

**Comment by Lenni009** [comment]
```
let headers = new Headers({});
                  ^

ReferenceError: Headers is not defined
```
Is this intended...? Also the action doesn't seem to be able to comment here. Could be because this is a PR from a fork.

In any case, it'd be good to have a dev branch where people can commit their stuff, and then we can do a PR to main which is then verified to not break during build

**Comment by Lenni009** [comment]
The PR comment issue is indeed related to the PR coming from a fork, see https://github.com/mshick/add-pr-comment#Features

However, it is weird that the build fails when it is definitely deployed to the site right now.

**Comment by Lenni009** [comment]
I bumped the node version up to 19 on the build action, maybe that fixes the build 🤔

**Comment by Khaoz-Topsy** [comment]
Good idea 💪

**Comment by Lenni009** [comment]
That worked. Thanks!

**Review by Khaoz-Topsy — APPROVED** [review]

**Pull request merged**
